In [9]:
import numpy as np

def jacobi_method(A, b, tolerance=1e-10, max_iterations=1000):
    # Tamanho da matriz
    n = len(A)
    
    # Matriz diagonal D, L e U (partes estritamente inferior e superior de A)
    D = np.diag(np.diag(A))  # Extrai a diagonal de A
    L = np.tril(A, -1)  # Parte triangular inferior
    U = np.triu(A, 1)  # Parte triangular superior
    
    # Vetor inicial de soluções (chutamos inicialmente como zero)
    x = np.zeros_like(b, dtype=np.double)
    
    # Criação do vetor para armazenar a solução anterior
    x_prev = np.zeros_like(x)
    
    print("Resolvendo o sistema Ax = b pelo método de Jacobi.")
    print(f"A matriz A é: \n{A}")
    print(f"O vetor b é: {b}\n")
    print(f"Matriz D: \n{D}")
    print(f"Matriz L: \n{L}")
    print(f"Matriz U: \n{U}\n")
    
    # Passo inicial: Iterações do método
    for iteration in range(max_iterations):
        print(f"Iteração {iteration + 1}:")
        for i in range(n):
            # Soma dos elementos da linha i de L e U multiplicados por x^(k)
            sum_LU = np.dot(L[i, :], x) + np.dot(U[i, :], x)
            
            # Aplicação da fórmula de Jacobi: 
            # x[i]^(k+1) = (b[i] - (L[i] + U[i]) * x) / D[i,i]
            x_prev[i] = (b[i] - sum_LU) / D[i, i]
            
            print(f"  - Equação para x[{i}]^(k+1): x[{i}] = (b[{i}] - (L[{i}] + U[{i}]) * x) / D[{i},{i}]")
            print(f"    => x[{i}] = ({b[i]} - {sum_LU}) / {D[i, i]}")
            print(f"    => x[{i}] = {x_prev[i]}")
        
        # Condição de parada: se a norma da diferença entre x e x_prev for pequena o suficiente
        norm = np.linalg.norm(x_prev - x, ord=np.inf)
        print(f"  - Norma da diferença: {norm}")
        if norm < tolerance:
            print("\nConvergência atingida!")
            break
        
        # Atualizar a solução
        x = x_prev.copy()
        print(f"  - Nova solução x: {x}\n")
    
    return x

# Exemplo de uso
A = np.array([[4, 1, 2], [3, 5, 1], [1, 1, 3]])

b = np.array([4, 7, 3])

# Resolver o sistema pelo método de Jacobi
solution = jacobi_method(A, b)

# solve the system with numpy to see the correct solution
solution_numpy = np.linalg.solve(A, b)

# Exibir a solução final
print("\nSolução final:")
print(solution)
print("\nSolução correta:")
print(solution_numpy)


Resolvendo o sistema Ax = b pelo método de Jacobi.
A matriz A é: 
[[4 1 2]
 [3 5 1]
 [1 1 3]]
O vetor b é: [4 7 3]

Matriz D: 
[[4 0 0]
 [0 5 0]
 [0 0 3]]
Matriz L: 
[[0 0 0]
 [3 0 0]
 [1 1 0]]
Matriz U: 
[[0 1 2]
 [0 0 1]
 [0 0 0]]

Iteração 1:
  - Equação para x[0]^(k+1): x[0] = (b[0] - (L[0] + U[0]) * x) / D[0,0]
    => x[0] = (4 - 0.0) / 4
    => x[0] = 1.0
  - Equação para x[1]^(k+1): x[1] = (b[1] - (L[1] + U[1]) * x) / D[1,1]
    => x[1] = (7 - 0.0) / 5
    => x[1] = 1.4
  - Equação para x[2]^(k+1): x[2] = (b[2] - (L[2] + U[2]) * x) / D[2,2]
    => x[2] = (3 - 0.0) / 3
    => x[2] = 1.0
  - Norma da diferença: 1.4
  - Nova solução x: [1.  1.4 1. ]

Iteração 2:
  - Equação para x[0]^(k+1): x[0] = (b[0] - (L[0] + U[0]) * x) / D[0,0]
    => x[0] = (4 - 3.4) / 4
    => x[0] = 0.15000000000000002
  - Equação para x[1]^(k+1): x[1] = (b[1] - (L[1] + U[1]) * x) / D[1,1]
    => x[1] = (7 - 4.0) / 5
    => x[1] = 0.6
  - Equação para x[2]^(k+1): x[2] = (b[2] - (L[2] + U[2]) * x) / D[2,2]
 

In [10]:
import numpy as np

def gauss_seidel_step_by_step(A, b, tolerance=1e-10, max_iterations=1000):
    # Tamanho da matriz
    n = len(A)
    
    # Matriz diagonal D, L e U (partes estritamente inferior e superior de A)
    D = np.diag(np.diag(A))  # Extrai a diagonal de A
    L = np.tril(A, -1)  # Parte triangular inferior
    U = np.triu(A, 1)  # Parte triangular superior
    
    # Vetor inicial de soluções (chutamos inicialmente como zero)
    x = np.zeros_like(b, dtype=np.double)
    
    print("Resolvendo o sistema Ax = b pelo método de Gauss-Seidel.")
    print(f"A matriz A é: \n{A}")
    print(f"O vetor b é: {b}\n")
    print(f"Matriz D: \n{D}")
    print(f"Matriz L: \n{L}")
    print(f"Matriz U: \n{U}\n")
    
    # Passo inicial: Iterações do método
    for iteration in range(max_iterations):
        print(f"Iteração {iteration + 1}:")
        x_old = x.copy()
        for i in range(n):
            # Soma dos elementos antes e depois de x[i]
            sum_L = np.dot(L[i, :], x)  # usa valores já atualizados de x
            sum_U = np.dot(U[i, :], x_old)  # usa valores da iteração anterior de x
            
            # Aplicação da fórmula de Gauss-Seidel: 
            # x[i]^(k+1) = (b[i] - (L[i] + U[i]) * x) / D[i,i]
            x[i] = (b[i] - sum_L - sum_U) / D[i, i]
            
            print(f"  - Equação para x[{i}]^(k+1): x[{i}] = (b[{i}] - sum_L - sum_U) / D[{i},{i}]")
            print(f"    => x[{i}] = ({b[i]} - {sum_L} - {sum_U}) / {D[i, i]}")
            print(f"    => x[{i}] = {x[i]}")
        
        # Condição de parada: se a norma da diferença entre x e x_old for pequena o suficiente
        norm = np.linalg.norm(x - x_old, ord=np.inf)
        print(f"  - Norma da diferença: {norm}")
        if norm < tolerance:
            print("\nConvergência atingida!")
            break
        
        print(f"  - Nova solução x: {x}\n")
    
    return x

# Exemplo de uso
A = np.array([[4, 1, 2], [3, 5, 1], [1, 1, 3]])

b = np.array([4, 7, 3])

# Resolver o sistema pelo método de Gauss-Seidel
solution = gauss_seidel_step_by_step(A, b)

# Exibir a solução final
print("\nSolução final:")
print(solution)

# solve the system with numpy to see the correct solution
solution_numpy = np.linalg.solve(A, b)
print("\nSolução correta:")
print(solution_numpy)

Resolvendo o sistema Ax = b pelo método de Gauss-Seidel.
A matriz A é: 
[[4 1 2]
 [3 5 1]
 [1 1 3]]
O vetor b é: [4 7 3]

Matriz D: 
[[4 0 0]
 [0 5 0]
 [0 0 3]]
Matriz L: 
[[0 0 0]
 [3 0 0]
 [1 1 0]]
Matriz U: 
[[0 1 2]
 [0 0 1]
 [0 0 0]]

Iteração 1:
  - Equação para x[0]^(k+1): x[0] = (b[0] - sum_L - sum_U) / D[0,0]
    => x[0] = (4 - 0.0 - 0.0) / 4
    => x[0] = 1.0
  - Equação para x[1]^(k+1): x[1] = (b[1] - sum_L - sum_U) / D[1,1]
    => x[1] = (7 - 3.0 - 0.0) / 5
    => x[1] = 0.8
  - Equação para x[2]^(k+1): x[2] = (b[2] - sum_L - sum_U) / D[2,2]
    => x[2] = (3 - 1.8 - 0.0) / 3
    => x[2] = 0.39999999999999997
  - Norma da diferença: 1.0
  - Nova solução x: [1.  0.8 0.4]

Iteração 2:
  - Equação para x[0]^(k+1): x[0] = (b[0] - sum_L - sum_U) / D[0,0]
    => x[0] = (4 - 0.0 - 1.6) / 4
    => x[0] = 0.6
  - Equação para x[1]^(k+1): x[1] = (b[1] - sum_L - sum_U) / D[1,1]
    => x[1] = (7 - 1.7999999999999998 - 0.39999999999999997) / 5
    => x[1] = 0.96
  - Equação para x[2]^(k+

In [8]:
import numpy as np

def conjugate_gradient_step_by_step(A, b, x0=None, tol=1e-10, max_iterations=1000):
    # Inicializar o vetor solução x0 com zeros se não fornecido
    if x0 is None:
        x0 = np.zeros_like(b)
    
    # Inicializando as variáveis
    x = x0
    r = b - A @ x  # Cálculo do resíduo inicial
    p = r.copy()    # Direção de busca inicial
    rs_old = np.dot(r, r)  # Produto interno r^T r
    
    print("Resolvendo o sistema Ax = b pelo método de Gradiente Conjugado.\n")
    print(f"A matriz A é:\n{A}\n")
    print(f"O vetor b é: {b}\n")
    print(f"Vetor inicial x^{0} = {x}\n")
    print(f"Resíduo inicial r^{0} = {r}\n")

    for k in range(max_iterations):
        print(f"Iteração {k + 1}:")
        
        # Passo 1: Cálculo de α_k
        Ap = A @ p
        alpha = rs_old / np.dot(p, Ap)
        print(f"  - α_{k} = {alpha}")
        
        # Passo 2: Atualização de x^(k+1)
        x = x + alpha * p
        print(f"  - Nova solução x^{k+1} = {x}")
        
        # Passo 3: Atualização do resíduo r^(k+1)
        r = r - alpha * Ap
        print(f"  - Novo resíduo r^{k+1} = {r}")
        
        # Verifica se o resíduo é suficientemente pequeno para parar
        rs_new = np.dot(r, r)
        if np.sqrt(rs_new) < tol:
            print("\nConvergência alcançada!\n")
            break
        
        # Passo 4: Atualização da direção de busca p^(k+1)
        beta = rs_new / rs_old
        p = r + beta * p
        print(f"  - β_{k} = {beta}")
        print(f"  - Nova direção de busca p^{k+1} = {p}\n")
        
        # Atualizar rs_old para a próxima iteração
        rs_old = rs_new

    return x

# Exemplo de uso
A = np.array([[4.0, 1.0]
                ,[1.0, 3.0]], dtype=float)

b = np.array([1, 2], dtype=float)

# Resolver o sistema pelo método de Gradiente Conjugado
x0 = np.zeros_like(b)  # Chute inicial
solution = conjugate_gradient_step_by_step(A, b, x0)

print("Solução final:")
print(solution)

# solve the system with numpy to see the correct solution
solution_numpy = np.linalg.solve(A, b)
print("\nSolução correta:")
print(solution_numpy)


Resolvendo o sistema Ax = b pelo método de Gradiente Conjugado.

A matriz A é:
[[4. 1.]
 [1. 3.]]

O vetor b é: [1. 2.]

Vetor inicial x^0 = [0. 0.]

Resíduo inicial r^0 = [1. 2.]

Iteração 1:
  - α_0 = 0.25
  - Nova solução x^1 = [0.25 0.5 ]
  - Novo resíduo r^1 = [-0.5   0.25]
  - β_0 = 0.0625
  - Nova direção de busca p^1 = [-0.4375  0.375 ]

Iteração 2:
  - α_1 = 0.36363636363636365
  - Nova solução x^2 = [0.09090909 0.63636364]
  - Novo resíduo r^2 = [0. 0.]

Convergência alcançada!

Solução final:
[0.09090909 0.63636364]

Solução correta:
[0.09090909 0.63636364]
