In [3]:
import numpy as np

def lu_decomposition(A):
    """
    Performs LU decomposition of a square matrix A.
    A = L * U, where L is a lower triangular matrix and U is an upper triangular matrix.
    
    Parameters:
    A : 2D numpy array (n x n) - Input matrix.
    
    Returns:
    L : 2D numpy array (n x n) - Lower triangular matrix.
    U : 2D numpy array (n x n) - Upper triangular matrix.
    """
    n = A.shape[0]
    L = np.eye(n)
    U = np.copy(A)

    print("Initial Matrix A:")
    print(A)
    
    for i in range(n):
        # Process each column for L and U
        print(f"\nProcessing column {i+1}:")
        for j in range(i+1, n):
            # Step: Compute L[j, i]
            L[j, i] = U[j, i] / U[i, i]
            print(f"L[{j},{i}] = U[{j},{i}] / U[{i},{i}] = {L[j, i]:.6f}")

            # Step: Update row of U
            U[j, i:] = U[j, i:] - L[j, i] * U[i, i:]
            print(f"Update U[{j},{i}:] by subtracting L[{j},{i}] * U[{i},{i}:]")
            print(f"Updated U matrix:\n{U}")
        
        # Display intermediate L and U matrices after processing each column
        print(f"\nL matrix after processing column {i+1}:\n{L}")
        print(f"U matrix after processing column {i+1}:\n{U}")

    print("\nFinal L matrix:\n", L)
    print("Final U matrix:\n", U)

    return L, U

# Example usage
A = np.array([[2, 3, 1],
              [6, 13, 5],
              [4, 9, 6]])

# convert A to float
A = A.astype(float)

L, U = lu_decomposition(A)

# Verify the decomposition
print("\nVerifying the decomposition:")
print("L * U:")
print(np.dot(L, U))
print("A:")
print(A)


Initial Matrix A:
[[ 2.  3.  1.]
 [ 6. 13.  5.]
 [ 4.  9.  6.]]

Processing column 1:
L[1,0] = U[1,0] / U[0,0] = 3.000000
Update U[1,0:] by subtracting L[1,0] * U[0,0:]
Updated U matrix:
[[2. 3. 1.]
 [0. 4. 2.]
 [4. 9. 6.]]
L[2,0] = U[2,0] / U[0,0] = 2.000000
Update U[2,0:] by subtracting L[2,0] * U[0,0:]
Updated U matrix:
[[2. 3. 1.]
 [0. 4. 2.]
 [0. 3. 4.]]

L matrix after processing column 1:
[[1. 0. 0.]
 [3. 1. 0.]
 [2. 0. 1.]]
U matrix after processing column 1:
[[2. 3. 1.]
 [0. 4. 2.]
 [0. 3. 4.]]

Processing column 2:
L[2,1] = U[2,1] / U[1,1] = 0.750000
Update U[2,1:] by subtracting L[2,1] * U[1,1:]
Updated U matrix:
[[2.  3.  1. ]
 [0.  4.  2. ]
 [0.  0.  2.5]]

L matrix after processing column 2:
[[1.   0.   0.  ]
 [3.   1.   0.  ]
 [2.   0.75 1.  ]]
U matrix after processing column 2:
[[2.  3.  1. ]
 [0.  4.  2. ]
 [0.  0.  2.5]]

Processing column 3:

L matrix after processing column 3:
[[1.   0.   0.  ]
 [3.   1.   0.  ]
 [2.   0.75 1.  ]]
U matrix after processing column 3

In [2]:
import numpy as np

def lu_decomposition_with_pivoting(A):
    """
    Performs LU decomposition with partial pivoting of a square matrix A.
    A = L * U, where L is a lower triangular matrix and U is an upper triangular matrix.
    
    Parameters:
    A : 2D numpy array (n x n) - Input matrix.
    
    Returns:
    L : 2D numpy array (n x n) - Lower triangular matrix.
    U : 2D numpy array (n x n) - Upper triangular matrix.
    P : 2D numpy array (n x n) - Permutation matrix.
    """
    n = A.shape[0]
    L = np.eye(n)
    U = np.copy(A)
    P = np.eye(n)  # Permutation matrix

    for i in range(n):
        # Partial Pivoting: Find the row with the maximum element in column i
        pivot = np.argmax(np.abs(U[i:, i])) + i
        if U[pivot, i] == 0:
            raise ValueError("Matrix is singular and cannot be decomposed.")
        
        # Swap rows in U and P
        if pivot != i:
            U[[i, pivot], :] = U[[pivot, i], :]
            P[[i, pivot], :] = P[[pivot, i], :]
            if i > 0:
                L[[i, pivot], :i] = L[[pivot, i], :i]  # Swap in L up to column i
        
        # Process each column for L and U
        for j in range(i+1, n):
            # Step: Compute L[j, i]
            L[j, i] = U[j, i] / U[i, i]

            # Step: Update row of U
            U[j, i:] = U[j, i:] - L[j, i] * U[i, i:]

    return P, L, U

# Example usage
A = np.array([[2, 3, 1],
              [6, 13, 5],
              [4, 9, 6]])

P, L, U = lu_decomposition_with_pivoting(A)
print("Permutation matrix P:\n", P)
print("Lower triangular matrix L:\n", L)
print("Upper triangular matrix U:\n", U)

# Verify the decomposition
print("\nVerifying the decomposition:")
print("P * A:")
print(np.dot(P, A))
print("L * U:")
print(np.dot(L, U))
print("A:")
print(A)


Permutation matrix P:
 [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
Lower triangular matrix L:
 [[ 1.          0.          0.        ]
 [ 0.33333333  1.          0.        ]
 [ 0.66666667 -0.          1.        ]]
Upper triangular matrix U:
 [[ 6 13  5]
 [ 0 -1  0]
 [ 0  0  2]]

Verifying the decomposition:
P * A:
[[ 6. 13.  5.]
 [ 2.  3.  1.]
 [ 4.  9.  6.]]
L * U:
[[ 6.         13.          5.        ]
 [ 2.          3.33333333  1.66666667]
 [ 4.          8.66666667  5.33333333]]
A:
[[ 2  3  1]
 [ 6 13  5]
 [ 4  9  6]]


In [4]:
import numpy as np

def lu_decomposition_markowitz(A):
    """
    Performs LU decomposition of a square matrix A using Markowitz pivoting.
    A = L * U, where L is a lower triangular matrix and U is an upper triangular matrix.
    
    Markowitz pivoting selects pivots to reduce fill-in.
    
    Parameters:
    A : 2D numpy array (n x n) - Input matrix.
    
    Returns:
    L : 2D numpy array (n x n) - Lower triangular matrix.
    U : 2D numpy array (n x n) - Upper triangular matrix.
    P : 2D numpy array (n x n) - Permutation matrix used for row swaps.
    """
    n = A.shape[0]
    L = np.eye(n)
    U = np.copy(A)
    P = np.eye(n)

    print("Initial Matrix A:")
    print(A)
    
    for i in range(n):
        # Markowitz pivoting: Find pivot based on minimum fill-in
        min_fill = np.inf
        pivot_row = i
        for j in range(i, n):
            fill = np.count_nonzero(U[j, :i]) * np.count_nonzero(U[:i, j])
            if fill < min_fill and U[j, i] != 0:
                min_fill = fill
                pivot_row = j
        
        # Step: Row swapping
        if pivot_row != i:
            print(f"\nStep {i+1}: Swap rows {i} and {pivot_row}")
            U[[i, pivot_row]] = U[[pivot_row, i]]
            P[[i, pivot_row]] = P[[pivot_row, i]]
            if i > 0:
                L[[i, pivot_row], :i] = L[[pivot_row, i], :i]

        # Display current U matrix after swap
        print(f"Matrix U after row swap (if any):\n{U}")
        print(f"Permutation matrix P after row swap (if any):\n{P}")

        # LU factorization
        for j in range(i+1, n):
            L[j, i] = U[j, i] / U[i, i]
            U[j, i:] = U[j, i:] - L[j, i] * U[i, i:]

        # Display L and U matrices after each step
        print(f"\nStep {i+1}: Update L and U matrices")
        print(f"L matrix:\n{L}")
        print(f"U matrix:\n{U}")

    print("\nFinal L matrix:\n", L)
    print("Final U matrix:\n", U)
    print("Final permutation matrix P:\n", P)

    return L, U, P

# Example usage
A = np.array([[4, 3, 8],
              [2, 1, 5],
              [6,8,7]])

L, U, P = lu_decomposition_markowitz(A)


Initial Matrix A:
[[4 3 8]
 [2 1 5]
 [6 8 7]]
Matrix U after row swap (if any):
[[4 3 8]
 [2 1 5]
 [6 8 7]]
Permutation matrix P after row swap (if any):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Step 1: Update L and U matrices
L matrix:
[[1.  0.  0. ]
 [0.5 1.  0. ]
 [1.5 0.  1. ]]
U matrix:
[[ 4  3  8]
 [ 0  0  1]
 [ 0  3 -5]]

Step 2: Swap rows 1 and 2
Matrix U after row swap (if any):
[[ 4  3  8]
 [ 0  3 -5]
 [ 0  0  1]]
Permutation matrix P after row swap (if any):
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]

Step 2: Update L and U matrices
L matrix:
[[1.  0.  0. ]
 [1.5 1.  0. ]
 [0.5 0.  1. ]]
U matrix:
[[ 4  3  8]
 [ 0  3 -5]
 [ 0  0  1]]
Matrix U after row swap (if any):
[[ 4  3  8]
 [ 0  3 -5]
 [ 0  0  1]]
Permutation matrix P after row swap (if any):
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]

Step 3: Update L and U matrices
L matrix:
[[1.  0.  0. ]
 [1.5 1.  0. ]
 [0.5 0.  1. ]]
U matrix:
[[ 4  3  8]
 [ 0  3 -5]
 [ 0  0  1]]

Final L matrix:
 [[1.  0.  0. ]
 [1.5 1.  0. ]
 [0.5 0.  1. ]]
Fi